<?php $cssVersion=(string)(@filemtime(ASSET_PATH.'/customer/portal.css')?:'1'); $uri=parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)?:''; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($title)?> | Udyam Customer Portal</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Cormorant+Garamond:wght@600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="<?=htmlspecialchars(url('/assets/customer/portal.css'))?>?v=<?=rawurlencode($cssVersion)?>"><script src="https://unpkg.com/lucide@latest"></script></head><body class="portal-body">
<aside class="portal-sidebar"><a class="portal-brand" href="<?=htmlspecialchars(url('/customer/dashboard'))?>"><img src="<?=htmlspecialchars(url('/uploads/media/original/home/udyam-ventures-logo-cropped.png'))?>" alt="Udyam Ventures"></a>
<nav><?php foreach([
'/customer/dashboard'=>['layout-dashboard','Dashboard'],'/customer/profile'=>['building-2','Company Profile'],'/customer/plans'=>['sparkles','Subscriptions'],'/customer/services'=>['briefcase-business','Services'],'/customer/applications'=>['clipboard-list','Applications'],'/customer/documents'=>['folder-open','Documents'],'/customer/notifications'=>['bell','Notifications'],'/customer/billing'=>['receipt-indian-rupee','Billing'],'/customer/activity'=>['history','Activity']
] as $path=>$item):?><a class="<?=str_contains($uri,$path)?'active':''?>" href="<?=htmlspecialchars(url($path))?>"><i data-lucide="<?=$item[0]?>"></i><span><?=$item[1]?></span></a><?php endforeach;?></nav>
<form method="post" action="<?=htmlspecialchars(url('/customer/logout'))?>"><?=csrf_field()?><button><i data-lucide="log-out"></i> Sign out</button></form></aside>
<button class="portal-scrim" type="button" aria-label="Close navigation"></button>
<div class="portal-main"><header class="portal-topbar"><button class="portal-menu" type="button" aria-label="Open navigation"><i data-lucide="menu"></i></button><div><span>Customer workspace</span><h1><?=htmlspecialchars($title)?></h1></div><a class="portal-avatar" href="<?=htmlspecialchars(url('/customer/profile'))?>"><?=htmlspecialchars(strtoupper(substr($customer['first_name'],0,1)))?></a></header>
<main class="portal-content"><?php if($m=\App\Core\Session::getFlash('success')):?><div class="portal-alert success"><?=htmlspecialchars($m)?></div><?php endif;?><?php if($m=\App\Core\Session::getFlash('error')):?><div class="portal-alert error"><?=htmlspecialchars($m)?></div><?php endif;?><?php require $content;?></main></div>
<script>lucide.createIcons();const body=document.body,menu=document.querySelector('.portal-menu'),scrim=document.querySelector('.portal-scrim');const closeMenu=()=>body.classList.remove('portal-menu-open');menu?.addEventListener('click',()=>body.classList.toggle('portal-menu-open'));scrim?.addEventListener('click',closeMenu);document.querySelectorAll('.portal-sidebar a').forEach(link=>link.addEventListener('click',closeMenu));document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu()});</script></body></html>
