<?php
$edit=!empty($plan['id']);
$value=static fn(string $key,mixed $default=''):string=>htmlspecialchars((string)($plan[$key]??$default));
$benefitLines=[];
foreach(json_decode($plan['benefits']??'[]',true)?:[] as $benefit){
    $benefitLines[]=is_array($benefit)?trim(($benefit['title']??'').' | '.($benefit['description']??'')):(string)$benefit;
}
?>
<div class="page-header"><div><span class="page-eyebrow">Customer Products</span><h2><?=$edit?'Edit':'Create New'?> Subscription Plan</h2><p>Configure pricing, instalments, taxes, positioning and customer benefits.</p></div><a class="btn" href="<?=htmlspecialchars(url('/admin/subscription-plans'))?>">Back to Plans</a></div>
<form class="subscription-builder" method="post" action="<?=htmlspecialchars(url($edit?'/admin/subscription-plans/update/'.$plan['id']:'/admin/subscription-plans/store'))?>"><?=csrf_field()?>
<div class="page-grid plan-builder-grid"><section class="card card-body"><div class="builder-heading"><i data-lucide="sparkles"></i><div><h3>Plan identity</h3><p>How this subscription appears in the customer portal.</p></div></div>
<div class="form-row"><div class="form-group col-8"><label>Plan name *</label><input class="form-control" name="name" value="<?=$value('name')?>" required></div><div class="form-group col-4"><label>Category</label><input class="form-control" name="category" value="<?=$value('category','Project Funding')?>"></div>
<div class="form-group col-6"><label>Plan subtitle</label><input class="form-control" name="subtitle" value="<?=$value('subtitle')?>" placeholder="Annual Plan - Option 1"></div><div class="form-group col-3"><label>Badge</label><input class="form-control" name="badge" value="<?=$value('badge')?>" placeholder="Best Value"></div><div class="form-group col-3"><label>Slug</label><input class="form-control" name="slug" value="<?=$value('slug')?>" placeholder="Auto-generated"></div>
<div class="form-group col-12"><label>Description</label><textarea class="form-control" rows="3" name="description"><?=$value('description')?></textarea></div><div class="form-group col-12"><label>Ideal for</label><textarea class="form-control" rows="2" name="ideal_for"><?=$value('ideal_for')?></textarea></div><div class="form-group col-12"><label>Pricing highlight</label><input class="form-control" name="highlight_text" value="<?=$value('highlight_text')?>" placeholder="₹15,000 now and ₹12,000 after 60 days"></div></div></section>
<aside class="card card-body"><div class="builder-heading"><i data-lucide="badge-indian-rupee"></i><div><h3>Price & publishing</h3><p>GST and instalment configuration.</p></div></div>
<div class="form-group"><label>Billing cycle</label><select class="form-control" name="billing_cycle"><?php foreach(['monthly','quarterly','half_yearly','yearly','one_time'] as $cycle):?><option value="<?=$cycle?>" <?=($plan['billing_cycle']??'yearly')===$cycle?'selected':''?>><?=ucwords(str_replace('_',' ',$cycle))?></option><?php endforeach;?></select></div>
<div class="form-row"><div class="form-group col-6"><label>Total plan price *</label><input class="form-control" type="number" min="0" step=".01" name="price" value="<?=$value('price')?>" required></div><div class="form-group col-6"><label>GST rate %</label><input class="form-control" type="number" min="0" max="100" step=".01" name="gst_rate" value="<?=$value('gst_rate',18)?>"></div></div>
<label class="premium-check"><input type="checkbox" name="gst_inclusive" value="1" <?=!empty($plan['gst_inclusive'])?'checked':''?>><span><b>Price includes GST</b><small>Checkout total remains the displayed price.</small></span></label>
<div class="form-row"><div class="form-group col-6"><label>Pay now</label><input class="form-control" type="number" min="0" step=".01" name="initial_payment" value="<?=$value('initial_payment')?>"></div><div class="form-group col-6"><label>Follow-up amount</label><input class="form-control" type="number" min="0" step=".01" name="followup_payment" value="<?=$value('followup_payment')?>"></div><div class="form-group col-12"><label>Follow-up due after days</label><input class="form-control" type="number" min="0" name="followup_due_days" value="<?=$value('followup_due_days')?>"></div></div>
<label class="premium-check"><input type="checkbox" name="featured" value="1" <?=!empty($plan['featured'])?'checked':''?>><span><b>Featured plan</b><small>Give this plan premium emphasis.</small></span></label>
<div class="form-row"><div class="form-group col-7"><label>Status</label><select class="form-control" name="status"><?php foreach(['draft','active','archived'] as $status):?><option value="<?=$status?>" <?=($plan['status']??'draft')===$status?'selected':''?>><?=ucfirst($status)?></option><?php endforeach;?></select></div><div class="form-group col-5"><label>Sort</label><input class="form-control" type="number" name="sort_order" value="<?=$value('sort_order',0)?>"></div></div></aside></div>
<section class="card card-body"><div class="builder-heading"><i data-lucide="list-checks"></i><div><h3>Member benefits</h3><p>Enter one benefit per line as <strong>Title | Description</strong>.</p></div></div><textarea class="form-control benefits-editor" rows="10" name="benefits" placeholder="Weekly Project Bulletins | Curated government, CSR, RFP and funding opportunities."><?=htmlspecialchars(implode("\n",$benefitLines))?></textarea><div class="form-group"><label>Disclaimer</label><textarea class="form-control" rows="2" name="disclaimer"><?=$value('disclaimer','Udyam does not guarantee project sanction. Submission charges are separate from subscription fees.')?></textarea></div></section>
<div class="builder-actions"><a class="btn" href="<?=htmlspecialchars(url('/admin/subscription-plans'))?>">Cancel</a><button class="btn btn-primary"><i data-lucide="save"></i> <?=$edit?'Update':'Create'?> Plan</button></div></form>
