<?php $record=$workspace['record'];$portalCustomer=$workspace['customer'];$tabs=['overview','applications','documents','billing','subscriptions','payments','activity','notifications'];?>
<div class="page-header"><div><h2><?=htmlspecialchars($record['title'])?></h2><p><?=htmlspecialchars($record['company']??'Customer workspace')?></p></div><a class="btn" href="<?=htmlspecialchars(url('/admin/customers'))?>">Back to Customers</a></div>
<div class="customer-workspace-tabs"><?php foreach($tabs as $name):?><a class="<?=$tab===$name?'active':''?>" href="?tab=<?=$name?>"><?=ucfirst($name)?></a><?php endforeach;?></div>
<?php if(!$portalCustomer):?><div class="alert alert-warning">This existing customer record is not linked to a customer portal account yet. Billing and portal activity will become available when the customer registers using <strong><?=htmlspecialchars($record['email']??'the same email')?></strong>.</div><?php else:?>
<?php if($tab==='overview'):?><div class="stats-grid"><div class="summary-card"><div class="summary-header"><span>Portal Account</span></div><div class="summary-value">Active</div></div><div class="summary-card"><div class="summary-header"><span>Applications</span></div><div class="summary-value"><?=count($workspace['applications'])?></div></div><div class="summary-card"><div class="summary-header"><span>Outstanding</span></div><div class="summary-value">₹<?=number_format((float)($workspace['dashboard']['outstanding']??0),0)?></div></div></div>
<?php elseif($tab==='applications'):?><div class="card table-responsive"><table class="table"><thead><tr><th>Number</th><th>Project</th><th>Status</th><th>Submitted</th></tr></thead><tbody><?php foreach($workspace['applications'] as $row):?><tr><td><?=$row['application_number']?></td><td><?=htmlspecialchars($row['project_name'])?></td><td><span class="badge"><?=$row['status']?></span></td><td><?=$row['submitted_at']?></td></tr><?php endforeach;?></tbody></table></div>
<?php elseif($tab==='documents'):?><div class="card table-responsive"><table class="table"><thead><tr><th>Document</th><th>Category</th><th>Source</th><th>Status</th></tr></thead><tbody><?php foreach($workspace['documents'] as $row):?><tr><td><?=htmlspecialchars($row['title'])?></td><td><?=$row['category']?></td><td><?=$row['source']?></td><td><?=$row['status']?></td></tr><?php endforeach;?></tbody></table></div>
<?php elseif($tab==='billing'):?><div class="page-grid"><form class="card card-body" method="post" action="<?=htmlspecialchars(url('/admin/customers/workspace/'.$record['id'].'/invoice'))?>"><?=csrf_field()?><h3>Generate Invoice</h3><div class="form-group"><label>Type</label><select class="form-control" name="invoice_type"><option value="service">Service</option><option value="subscription">Subscription</option></select></div><div class="form-group"><label>Description</label><input class="form-control" name="description" required></div><div class="form-row"><div class="form-group col-6"><label>Amount</label><input class="form-control" type="number" step=".01" name="amount" required></div><div class="form-group col-6"><label>GST %</label><input class="form-control" type="number" step=".01" name="gst_rate" value="18"></div></div><div class="form-group"><label>Due Date</label><input class="form-control" type="date" name="due_date" required></div><input type="hidden" name="subscription_id" value=""><input type="hidden" name="service_request_id" value=""><input type="hidden" name="billing_cycle"><textarea class="form-control" name="notes" placeholder="Invoice notes"></textarea><button class="btn btn-primary">Generate Invoice</button></form><div class="card table-responsive"><table class="table"><thead><tr><th>Invoice</th><th>Total</th><th>Status</th></tr></thead><tbody><?php foreach($workspace['invoices'] as $row):?><tr><td><?=$row['invoice_number']?></td><td>₹<?=number_format($row['total_amount'],2)?></td><td><?=$row['status']?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php elseif($tab==='payments'):?><div class="page-grid"><form class="card card-body" method="post" action="<?=htmlspecialchars(url('/admin/customers/workspace/'.$record['id'].'/payment'))?>"><?=csrf_field()?><h3>Record Payment</h3><div class="form-group"><label>Invoice</label><select class="form-control" name="invoice_id"><?php foreach($workspace['invoices'] as $row):?><option value="<?=$row['id']?>"><?=$row['invoice_number']?> — ₹<?=$row['total_amount']?></option><?php endforeach;?></select></div><div class="form-group"><label>Amount</label><input class="form-control" type="number" step=".01" name="amount" required></div><div class="form-group"><label>Method</label><select class="form-control" name="method"><?php foreach(['bank_transfer','upi','cash','cheque','card','gateway','adjustment'] as $v):?><option><?=$v?></option><?php endforeach;?></select></div><input class="form-control" type="datetime-local" name="payment_date"><input class="form-control" name="transaction_id" placeholder="Transaction ID"><textarea class="form-control" name="notes" placeholder="Notes"></textarea><button class="btn btn-primary">Record Payment</button></form><div class="card table-responsive"><table class="table"><thead><tr><th>Date</th><th>Invoice</th><th>Amount</th><th>Method</th></tr></thead><tbody><?php foreach($workspace['payments'] as $row):?><tr><td><?=$row['payment_date']?></td><td><?=$row['invoice_number']?></td><td>₹<?=$row['amount']?></td><td><?=$row['method']?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php else:?><div class="card card-body"><h3><?=ucfirst($tab)?></h3><pre style="white-space:pre-wrap"><?=htmlspecialchars(json_encode($workspace[$tab]??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE))?></pre></div><?php endif;?>
<?php endif;?>
