<?php
$record = $workspace['record'];
$partner = $workspace['customer'];
$tabs = [
    'overview' => ['layout-dashboard', 'Overview'],
    'subscriptions' => ['badge-indian-rupee', 'Subscriptions'],
    'billing' => ['receipt-indian-rupee', 'Billing'],
    'payments' => ['credit-card', 'Payments'],
    'applications' => ['clipboard-list', 'Applications'],
    'documents' => ['folder-open', 'Documents'],
    'notifications' => ['bell', 'Notifications'],
    'activity' => ['history', 'Activity'],
];
$partnerName = trim((string) ($partner['first_name'] ?? $record['title']) . ' ' . (string) ($partner['last_name'] ?? ''));
$company = (string) ($partner['company_name'] ?? $record['company'] ?? 'Individual partner');
$dashboard = $workspace['dashboard'] ?? [];
$applications = $workspace['applications'] ?? [];
$documents = $workspace['documents'] ?? [];
$subscriptions = $workspace['subscriptions'] ?? [];
$invoices = $workspace['invoices'] ?? [];
$payments = $workspace['payments'] ?? [];
$plans = $workspace['plans'] ?? [];
$notifications = $workspace['notifications'] ?? [];
$activity = $workspace['activity'] ?? [];
$activeSubscription = null;
foreach ($subscriptions as $subscription) if (($subscription['status'] ?? '') === 'active') { $activeSubscription = $subscription; break; }
$badge = static fn (string $value): string => htmlspecialchars(ucwords(str_replace('_', ' ', $value)));
?>

<div class="partner-workspace">
    <div class="partner-workspace-header">
        <a class="workspace-back" href="<?= htmlspecialchars(url('/admin/customers')) ?>"><i data-lucide="arrow-left"></i> Partners</a>
        <div class="workspace-actions">
            <?php if ($partner): ?><a class="btn btn-primary" href="?tab=billing#new-invoice"><i data-lucide="file-plus-2"></i> Create invoice</a><?php endif; ?>
            <a class="btn" href="<?= htmlspecialchars(url('/admin/customers/edit/' . $record['id'])) ?>"><i data-lucide="pencil"></i> Edit partner</a>
        </div>
    </div>

    <section class="partner-profile-hero">
        <div class="partner-avatar-large"><?= htmlspecialchars(strtoupper(mb_substr($partnerName ?: (string) $record['title'], 0, 1))) ?></div>
        <div class="partner-profile-copy"><span>Partner account</span><h2><?= htmlspecialchars($partnerName ?: (string) $record['title']) ?></h2><p><?= htmlspecialchars($company) ?> · <?= htmlspecialchars((string) ($partner['email'] ?? $record['email'] ?? 'Email not added')) ?></p><div class="partner-profile-tags">
            <b class="tag <?= $partner ? 'success' : 'neutral' ?>"><i data-lucide="<?= $partner ? 'circle-check' : 'link-2-off' ?>"></i><?= $partner ? 'Portal linked' : 'Portal not linked' ?></b>
            <?php if ($partner): ?><b class="tag <?= !empty($partner['email_verified_at']) ? 'success' : 'warning' ?>"><i data-lucide="mail-check"></i><?= !empty($partner['email_verified_at']) ? 'Email verified' : 'Email verification pending' ?></b><?php endif; ?>
            <?php if ($activeSubscription): ?><b class="tag purple"><i data-lucide="sparkles"></i><?= htmlspecialchars($activeSubscription['plan_name']) ?></b><?php endif; ?>
        </div></div>
        <?php if ($partner): ?><div class="partner-hero-contact"><span>Contact</span><strong><?= htmlspecialchars((string) ($partner['mobile'] ?: 'Mobile not added')) ?></strong><small><?= htmlspecialchars((string) ($partner['preferred_communication'] ?: 'email')) ?> preferred</small></div><?php endif; ?>
    </section>

    <?php if (!$partner): ?>
        <section class="partner-link-notice"><i data-lucide="circle-alert"></i><div><strong>This partner does not have a portal account yet.</strong><p>When they register with <b><?= htmlspecialchars((string) ($record['email'] ?? 'their email address')) ?></b>, their subscriptions, billing, documents and activity will appear here automatically.</p></div><a class="btn btn-primary" href="<?= htmlspecialchars(url('/customer/register')) ?>" target="_blank" rel="noopener">Open registration <i data-lucide="arrow-up-right"></i></a></section>
    <?php else: ?>
        <nav class="customer-workspace-tabs" aria-label="Partner workspace sections"><?php foreach ($tabs as $key => [$icon, $label]): ?><a class="<?= $tab === $key ? 'active' : '' ?>" href="?tab=<?= htmlspecialchars($key) ?>"><i data-lucide="<?= $icon ?>"></i><?= htmlspecialchars($label) ?></a><?php endforeach; ?></nav>

        <?php if ($tab === 'overview'): ?>
            <section class="workspace-metrics">
                <article><span><i data-lucide="badge-indian-rupee"></i> Active membership</span><strong><?= htmlspecialchars($activeSubscription['plan_name'] ?? 'No active plan') ?></strong><a href="?tab=subscriptions">Manage subscription <i data-lucide="arrow-up-right"></i></a></article>
                <article><span><i data-lucide="clipboard-list"></i> Applications</span><strong><?= count($applications) ?></strong><a href="?tab=applications">Review applications <i data-lucide="arrow-up-right"></i></a></article>
                <article><span><i data-lucide="wallet-cards"></i> Outstanding</span><strong>₹<?= number_format((float) ($dashboard['outstanding'] ?? 0), 0) ?></strong><a href="?tab=billing">Open billing <i data-lucide="arrow-up-right"></i></a></article>
                <article><span><i data-lucide="folder-check"></i> Documents</span><strong><?= count($documents) ?></strong><a href="?tab=documents">View documents <i data-lucide="arrow-up-right"></i></a></article>
            </section>
            <div class="workspace-overview-grid">
                <section class="workspace-panel"><div class="workspace-panel-heading"><div><span>Partner details</span><h3>Company &amp; contact information</h3></div><a href="<?= htmlspecialchars(url('/admin/customers/edit/' . $record['id'])) ?>">Edit</a></div><dl class="partner-details"><div><dt>Company</dt><dd><?= htmlspecialchars($company) ?></dd></div><div><dt>Contact person</dt><dd><?= htmlspecialchars((string) ($partner['contact_person'] ?: $partnerName)) ?></dd></div><div><dt>Email</dt><dd><?= htmlspecialchars((string) $partner['email']) ?></dd></div><div><dt>Mobile</dt><dd><?= htmlspecialchars((string) ($partner['mobile'] ?: 'Not added')) ?></dd></div><div><dt>GST</dt><dd><?= htmlspecialchars((string) ($partner['gst_number'] ?: 'Not added')) ?></dd></div><div><dt>Location</dt><dd><?= htmlspecialchars(trim((string) ($partner['city'] ?? '') . ', ' . (string) ($partner['state'] ?? ''), ', ' ) ?: 'Not added') ?></dd></div></dl></section>
                <section class="workspace-panel"><div class="workspace-panel-heading"><div><span>Recent activity</span><h3>Latest partner updates</h3></div><a href="?tab=activity">View all</a></div><div class="workspace-timeline"><?php if (!$activity): ?><div class="workspace-empty"><i data-lucide="history"></i>No activity yet.</div><?php else: foreach (array_slice($activity, 0, 5) as $item): ?><div><i></i><span><strong><?= htmlspecialchars(ucwords(str_replace('_', ' ', (string) $item['action']))) ?></strong><small><?= htmlspecialchars((string) ($item['description'] ?? '')) ?> · <?= htmlspecialchars(date('d M Y', strtotime((string) $item['created_at']))) ?></small></span></div><?php endforeach; endif; ?></div></section>
            </div>
        <?php elseif ($tab === 'subscriptions'): ?>
            <section class="workspace-panel"><div class="workspace-panel-heading"><div><span>Memberships</span><h3>Subscription history</h3><p>Active access, pending checkouts and expiry dates are all visible here.</p></div><a class="btn btn-primary" href="<?= htmlspecialchars(url('/admin/subscription-plans')) ?>"><i data-lucide="layers-3"></i> Manage plans</a></div><div class="workspace-subscription-grid"><?php if (!$subscriptions): ?><div class="workspace-empty"><i data-lucide="badge-indian-rupee"></i>No subscription has been assigned yet.</div><?php else: foreach ($subscriptions as $item): ?><article class="workspace-subscription-card"><span class="status-pill <?= htmlspecialchars((string) $item['status']) ?>"><?= $badge((string) $item['status']) ?></span><h3><?= htmlspecialchars((string) $item['plan_name']) ?></h3><p><?= htmlspecialchars(ucfirst(str_replace('_', ' ', (string) $item['billing_cycle']))) ?> membership</p><strong>₹<?= number_format((float) $item['amount'], 0) ?></strong><dl><div><dt>Started</dt><dd><?= htmlspecialchars((string) ($item['starts_at'] ?: '—')) ?></dd></div><div><dt>Expires</dt><dd><?= htmlspecialchars((string) ($item['expires_at'] ?: '—')) ?></dd></div></dl></article><?php endforeach; endif; ?></div></section>
        <?php elseif ($tab === 'applications'): ?>
            <section class="workspace-panel"><div class="workspace-panel-heading"><div><span>Service delivery</span><h3>Applications</h3><p>Track every service request, assignment and current delivery stage.</p></div></div><div class="table-responsive"><table class="table workspace-table"><thead><tr><th>Application</th><th>Service</th><th>Assigned consultant</th><th>Status</th><th>Submitted</th></tr></thead><tbody><?php if (!$applications): ?><tr><td colspan="5" class="workspace-empty-cell">No applications have been submitted.</td></tr><?php else: foreach ($applications as $row): ?><tr><td><strong><?= htmlspecialchars((string) $row['application_number']) ?></strong><small><?= htmlspecialchars((string) ($row['project_name'] ?: 'Untitled project')) ?></small></td><td><?= htmlspecialchars((string) $row['service_title']) ?></td><td><?= htmlspecialchars(trim((string) ($row['assigned_first_name'] ?? '') . ' ' . (string) ($row['assigned_last_name'] ?? '')) ?: 'Not assigned') ?></td><td><span class="status-pill <?= htmlspecialchars((string) $row['status']) ?>"><?= $badge((string) $row['status']) ?></span></td><td><?= htmlspecialchars(date('d M Y', strtotime((string) $row['submitted_at']))) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></section>
        <?php elseif ($tab === 'documents'): ?>
            <section class="workspace-panel"><div class="workspace-panel-heading"><div><span>Secure files</span><h3>Documents</h3><p>Documents uploaded by the partner and the Udyam team.</p></div></div><div class="workspace-document-grid"><?php if (!$documents): ?><div class="workspace-empty"><i data-lucide="folder-open"></i>No documents have been uploaded.</div><?php else: foreach ($documents as $row): ?><article><span><i data-lucide="file-text"></i></span><div><strong><?= htmlspecialchars((string) $row['title']) ?></strong><small><?= $badge((string) $row['category']) ?> · <?= $badge((string) $row['source']) ?> · <?= $badge((string) $row['status']) ?></small></div><span class="document-date"><?= htmlspecialchars(date('d M Y', strtotime((string) $row['created_at']))) ?></span><div class="workspace-document-actions"><a href="<?= htmlspecialchars(url('/admin/customers/workspace/'.$record['id'].'/documents/'.$row['id'].'/view')) ?>" target="_blank" rel="noopener" title="View document"><i data-lucide="eye"></i><span>View</span></a><a class="download" href="<?= htmlspecialchars(url('/admin/customers/workspace/'.$record['id'].'/documents/'.$row['id'].'/download')) ?>" title="Download document"><i data-lucide="download"></i><span>Download</span></a></div></article><?php endforeach; endif; ?></div></section>
        <?php elseif ($tab === 'billing'): ?>
            <div class="workspace-action-grid"><section class="workspace-panel" id="new-invoice"><div class="workspace-panel-heading"><div><span>Billing action</span><h3>Create an invoice</h3><p>For an offline membership payment, choose Subscription invoice and its plan.</p></div></div><form method="post" action="<?= htmlspecialchars(url('/admin/customers/workspace/' . $record['id'] . '/invoice')) ?>" class="workspace-form" data-invoice-form><?= csrf_field() ?><label><span>Invoice type</span><select class="form-control" name="invoice_type" data-invoice-type><option value="service">Service invoice</option><option value="subscription">Subscription invoice</option></select></label><label data-plan-selector hidden><span>Subscription plan</span><select class="form-control" name="plan_id" data-plan-input><option value="">Select a plan</option><?php foreach($plans as $plan): ?><option value="<?= (int)$plan['id'] ?>"><?= htmlspecialchars((string)$plan['name']) ?> · ₹<?= number_format((float)$plan['price'],0) ?> / <?= htmlspecialchars((string)$plan['billing_cycle']) ?></option><?php endforeach; ?></select><small>Selecting this plan creates a pending membership. It becomes active when the invoice is fully paid.</small></label><label><span>What is this invoice for?</span><input class="form-control" name="description" placeholder="e.g. Annual Project Funding membership" required></label><div class="form-row"><label class="form-group col-6"><span>Amount (₹)</span><input class="form-control" type="number" min="1" step=".01" name="amount" required></label><label class="form-group col-6"><span>GST %</span><input class="form-control" type="number" min="0" max="100" step=".01" name="gst_rate" value="18"></label></div><label><span>Due date</span><input class="form-control" type="date" name="due_date" required></label><input type="hidden" name="subscription_id"><input type="hidden" name="service_request_id"><input type="hidden" name="billing_cycle"><label><span>Note for partner <em>Optional</em></span><textarea class="form-control" name="notes" placeholder="Payment instructions or a helpful note"></textarea></label><button class="btn btn-primary" type="submit"><i data-lucide="send"></i> Generate &amp; issue invoice</button></form></section>
            <section class="workspace-panel"><div class="workspace-panel-heading"><div><span>Invoice register</span><h3>Invoices</h3></div></div><div class="table-responsive"><table class="table workspace-table"><thead><tr><th>Invoice</th><th>For</th><th>Due</th><th>Total</th><th>Status</th></tr></thead><tbody><?php if (!$invoices): ?><tr><td colspan="5" class="workspace-empty-cell">No invoices have been issued.</td></tr><?php else: foreach ($invoices as $row): ?><tr><td><strong><?= htmlspecialchars((string) $row['invoice_number']) ?></strong><small><?= htmlspecialchars((string) $row['issue_date']) ?></small></td><td><?= htmlspecialchars((string) ($row['subscription_name'] ?: $row['service_name'] ?: ucfirst((string) $row['invoice_type']))) ?><?php if($row['status']==='paid'&&empty($row['subscription_id'])): ?><form method="post" action="<?= htmlspecialchars(url('/admin/customers/workspace/'.$record['id'].'/activate-subscription')) ?>" class="legacy-membership-form"><?= csrf_field() ?><input type="hidden" name="invoice_id" value="<?= (int)$row['id'] ?>"><select name="plan_id" required><option value="">Activate a plan…</option><?php foreach($plans as $plan): ?><option value="<?= (int)$plan['id'] ?>"><?= htmlspecialchars((string)$plan['name']) ?></option><?php endforeach; ?></select><button type="submit">Activate membership</button></form><?php endif; ?></td><td><?= htmlspecialchars((string) $row['due_date']) ?></td><td>₹<?= number_format((float) $row['total_amount'], 2) ?></td><td><span class="status-pill <?= htmlspecialchars((string) $row['status']) ?>"><?= $badge((string) $row['status']) ?></span></td></tr><?php endforeach; endif; ?></tbody></table></div></section></div>
            <script>document.addEventListener('DOMContentLoaded',()=>{const type=document.querySelector('[data-invoice-type]'),selector=document.querySelector('[data-plan-selector]'),plan=document.querySelector('[data-plan-input]');const sync=()=>{const subscription=type?.value==='subscription';if(selector)selector.hidden=!subscription;if(plan)plan.required=subscription;};type?.addEventListener('change',sync);sync();});</script>
        <?php elseif ($tab === 'payments'): ?>
            <div class="workspace-action-grid"><section class="workspace-panel"><div class="workspace-panel-heading"><div><span>Payment action</span><h3>Record a payment</h3><p>Use this for offline transfers, UPI, cash, cheques or corrections.</p></div></div><?php if (!$invoices): ?><div class="workspace-empty"><i data-lucide="receipt-text"></i>Create an invoice before recording a payment.</div><?php else: ?><form method="post" action="<?= htmlspecialchars(url('/admin/customers/workspace/' . $record['id'] . '/payment')) ?>" class="workspace-form"><?= csrf_field() ?><label><span>Invoice</span><select class="form-control" name="invoice_id"><?php foreach ($invoices as $row): ?><option value="<?= (int) $row['id'] ?>"><?= htmlspecialchars((string) $row['invoice_number']) ?> — ₹<?= number_format((float) $row['total_amount'], 2) ?></option><?php endforeach; ?></select></label><div class="form-row"><label class="form-group col-6"><span>Amount (₹)</span><input class="form-control" type="number" step=".01" min="1" name="amount" required></label><label class="form-group col-6"><span>Method</span><select class="form-control" name="method"><?php foreach (['bank_transfer'=>'Bank transfer','upi'=>'UPI','cash'=>'Cash','cheque'=>'Cheque','card'=>'Card','gateway'=>'Payment gateway','adjustment'=>'Adjustment'] as $value => $label): ?><option value="<?= $value ?>"><?= $label ?></option><?php endforeach; ?></select></label></div><label><span>Payment date &amp; time</span><input class="form-control" type="datetime-local" name="payment_date"></label><label><span>Transaction reference <em>Optional</em></span><input class="form-control" name="transaction_id" placeholder="Bank / UPI / cheque reference"></label><label><span>Internal note <em>Optional</em></span><textarea class="form-control" name="notes" placeholder="Add any useful context"></textarea></label><button class="btn btn-primary" type="submit"><i data-lucide="check-circle-2"></i> Record payment</button></form><?php endif; ?></section>
            <section class="workspace-panel"><div class="workspace-panel-heading"><div><span>Payment register</span><h3>Payments</h3></div></div><div class="table-responsive"><table class="table workspace-table"><thead><tr><th>Date</th><th>Invoice</th><th>Reference</th><th>Method</th><th>Amount</th><th>Status</th></tr></thead><tbody><?php if (!$payments): ?><tr><td colspan="6" class="workspace-empty-cell">No payments have been recorded.</td></tr><?php else: foreach ($payments as $row): ?><tr><td><?= htmlspecialchars(date('d M Y', strtotime((string) $row['payment_date']))) ?></td><td><?= htmlspecialchars((string) $row['invoice_number']) ?></td><td><?= htmlspecialchars((string) ($row['transaction_id'] ?: '—')) ?></td><td><?= $badge((string) $row['method']) ?></td><td>₹<?= number_format((float) $row['amount'], 2) ?></td><td><span class="status-pill <?= htmlspecialchars((string) $row['status']) ?>"><?= $badge((string) $row['status']) ?></span></td></tr><?php endforeach; endif; ?></tbody></table></div></section></div>
        <?php elseif ($tab === 'notifications'): ?>
            <section class="workspace-panel"><div class="workspace-panel-heading"><div><span>Partner communication</span><h3>Notifications</h3><p>Portal messages, billing updates and document requests sent to this partner.</p></div></div><div class="workspace-notifications"><?php if (!$notifications): ?><div class="workspace-empty"><i data-lucide="bell-off"></i>No notifications have been sent.</div><?php else: foreach ($notifications as $item): ?><article class="<?= empty($item['read_at']) ? 'unread' : '' ?>"><i data-lucide="bell-ring"></i><div><span><?= $badge((string) $item['type']) ?></span><strong><?= htmlspecialchars((string) $item['title']) ?></strong><p><?= htmlspecialchars((string) $item['message']) ?></p><small><?= htmlspecialchars(date('d M Y, h:i A', strtotime((string) $item['created_at']))) ?></small></div></article><?php endforeach; endif; ?></div></section>
        <?php elseif ($tab === 'activity'): ?>
            <section class="workspace-panel"><div class="workspace-panel-heading"><div><span>Audit trail</span><h3>Partner activity</h3><p>Secure log of profile changes, applications, documents, invoices and payments.</p></div></div><div class="workspace-timeline large"><?php if (!$activity): ?><div class="workspace-empty"><i data-lucide="history"></i>No partner activity is available yet.</div><?php else: foreach ($activity as $item): ?><div><i></i><span><strong><?= htmlspecialchars(ucwords(str_replace('_', ' ', (string) $item['action']))) ?></strong><small><?= htmlspecialchars((string) ($item['description'] ?? '')) ?> · <?= htmlspecialchars(date('d M Y, h:i A', strtotime((string) $item['created_at']))) ?></small></span></div><?php endforeach; endif; ?></div></section>
        <?php endif; ?>
    <?php endif; ?>
</div>
