<?php
$errors=\App\Core\Session::get('errors',[]);$old=\App\Core\Session::get('old',[]);\App\Core\Session::forget('errors');\App\Core\Session::forget('old');
$v=array_merge($record,$old);$edit=$mode==='edit';$get=static fn($key,$default='')=>(string)($v[$key]??$default);
?>
<div class="page-header"><div><span class="staff-eyebrow">Staff Management</span><h2><?=htmlspecialchars($title)?></h2><p><?= $edit?'Update employment, contact and profile information.':'A Digital Business Card and QR code will be created automatically.'?></p></div><a class="btn" href="<?=htmlspecialchars(url($edit?'/admin/staff/'.$record['id']:'/admin/staff'))?>">Cancel</a></div>
<form class="staff-form" method="post" enctype="multipart/form-data" action="<?=htmlspecialchars(url($edit?'/admin/staff/'.$record['id'].'/update':'/admin/staff/store'))?>"><?=csrf_field()?>
<section class="card staff-form-section"><div class="staff-section-title"><i data-lucide="badge-check"></i><div><h3>Identity & employment</h3><p>Core employee record and organization placement.</p></div></div><div class="staff-form-grid">
<?php $fields=['employee_code'=>['Employee Code *','text',$edit?'':$suggestedCode],'first_name'=>['First Name *','text',''],'last_name'=>['Last Name *','text',''],'display_name'=>['Display Name','text',''],'designation'=>['Designation *','text',''],'department'=>['Department *','text',''],'date_of_joining'=>['Date of Joining *','date','']];foreach($fields as $name=>$meta):?><div class="form-group"><label><?=$meta[0]?></label><input class="form-control" type="<?=$meta[1]?>" name="<?=$name?>" value="<?=htmlspecialchars($get($name,$meta[2]))?>"><?php if(isset($errors[$name][0])):?><span class="invalid-feedback d-block"><?=htmlspecialchars($errors[$name][0])?></span><?php endif?></div><?php endforeach?>
<div class="form-group"><label>Employment Type *</label><select class="form-control" name="employment_type"><?php foreach(['full_time'=>'Full Time','part_time'=>'Part Time','contract'=>'Contract','intern'=>'Intern','consultant'=>'Consultant'] as $key=>$label):?><option value="<?=$key?>" <?=$get('employment_type','full_time')===$key?'selected':''?>><?=$label?></option><?php endforeach?></select></div>
<div class="form-group"><label>Reporting Manager</label><select class="form-control" name="reporting_manager_id"><option value="">No manager</option><?php foreach($managers as $manager):?><option value="<?=$manager['id']?>" <?=$get('reporting_manager_id')===(string)$manager['id']?'selected':''?>><?=htmlspecialchars($manager['display_name'].' · '.$manager['designation'])?></option><?php endforeach?></select></div>
<div class="form-group"><label>Status *</label><select class="form-control" name="status"><?php foreach($statuses as $item):?><option value="<?=$item?>" <?=$get('status','active')===$item?'selected':''?>><?=ucwords(str_replace('_',' ',$item))?></option><?php endforeach?></select></div></div></section>
<section class="card staff-form-section"><div class="staff-section-title"><i data-lucide="image"></i><div><h3>Profile photo</h3><p>Strongly recommended. Uploads are stored in the existing Media Library.</p></div></div><div class="staff-photo-editor"><?php if(!empty($v['photo_filename'])):?><img src="<?=htmlspecialchars(media_url(['folder'=>$v['photo_folder'],'filename'=>$v['photo_filename']]))?>" alt="Current profile photo"><?php else:?><div class="staff-photo-placeholder"><i data-lucide="user-round"></i></div><?php endif?><div><div class="form-group"><label>Upload / replace photo</label><input class="form-control" type="file" name="profile_photo" accept="image/jpeg,image/png,image/webp,image/gif"><small>Square JPG, PNG or WebP works best.</small></div><div class="form-group"><label>Or select from Media Library</label><select class="form-control" name="profile_photo_media_id"><option value="">No selected image</option><?php foreach($mediaImages as $image):?><option value="<?=$image['id']?>" <?=$get('profile_photo_media_id')===(string)$image['id']?'selected':''?>><?=htmlspecialchars($image['title']?:$image['original_name'])?></option><?php endforeach?></select></div><?php if(isset($errors['profile_photo'][0])):?><span class="invalid-feedback d-block"><?=htmlspecialchars($errors['profile_photo'][0])?></span><?php endif?></div></div></section>
<section class="card staff-form-section"><div class="staff-section-title"><i data-lucide="shield-check"></i><div><h3>Admin portal access</h3><p>The staff member is stored in the users table. Enable login and assign restrictive roles when access is required.</p></div></div><?php $portalEnabled=(bool)($v['portal_access']??(($v['account_status']??'inactive')==='active'));$chosenRoles=array_map('intval',(array)($v['role_ids']??$selectedRoleIds));?><label class="staff-access-toggle"><input type="checkbox" name="portal_access" value="1" <?=$portalEnabled?'checked':''?>><span><i data-lucide="check"></i></span><div><strong>Allow this staff member to log in</strong><small>Disabling this blocks login without affecting the public business card.</small></div></label><div class="staff-form-grid access-fields"><div class="form-group"><label><?=$edit?'New Password':'Temporary Password'?><?=$edit?' (leave blank to keep current)':''?></label><input class="form-control" type="password" name="password" autocomplete="new-password"><?php if(isset($errors['password'][0])):?><span class="invalid-feedback d-block"><?=htmlspecialchars($errors['password'][0])?></span><?php endif?></div><div class="form-group"><label>Assigned Roles</label><div class="staff-role-options"><?php if($roles===[]):?><small>Create roles under Settings → Roles & Permissions.</small><?php else:foreach($roles as$role):?><label><input type="checkbox" name="role_ids[]" value="<?=$role['id']?>" <?=in_array((int)$role['id'],$chosenRoles,true)?'checked':''?>><span><?=htmlspecialchars($role['name'])?></span></label><?php endforeach;endif?></div></div></div></section>
<section class="card staff-form-section"><div class="staff-section-title"><i data-lucide="contact"></i><div><h3>Contact & location</h3><p>Work contact details used by the directory and business card.</p></div></div><div class="staff-form-grid"><?php foreach(['email'=>['Email *','email'],'mobile'=>['Mobile *','tel'],'alternate_mobile'=>['Alternate Mobile','tel'],'whatsapp_number'=>['WhatsApp Number','tel'],'office_extension'=>['Office Extension / Phone','text'],'office_location'=>['Office Location','text'],'linkedin_url'=>['LinkedIn URL','url'],'website_url'=>['Website URL','url']] as $name=>$meta):?><div class="form-group"><label><?=$meta[0]?></label><input class="form-control" type="<?=$meta[1]?>" name="<?=$name?>" value="<?=htmlspecialchars($get($name))?>"><?php if(isset($errors[$name][0])):?><span class="invalid-feedback d-block"><?=htmlspecialchars($errors[$name][0])?></span><?php endif?></div><?php endforeach?><div class="form-group span-2"><label>Office Address</label><textarea class="form-control" rows="3" name="address"><?=htmlspecialchars($get('address'))?></textarea></div><div class="form-group span-2"><label>Emergency Contact</label><textarea class="form-control" rows="2" name="emergency_contact" placeholder="Name, relationship and phone number"><?=htmlspecialchars($get('emergency_contact'))?></textarea></div></div></section>
<section class="card staff-form-section"><div class="staff-section-title"><i data-lucide="notebook-pen"></i><div><h3>Professional profile</h3><p>Introduction, capabilities and internal context.</p></div></div><div class="staff-form-grid"><div class="form-group span-2"><label>Bio / Short Introduction</label><textarea class="form-control" rows="4" name="bio"><?=htmlspecialchars($get('bio'))?></textarea></div><div class="form-group span-2"><label>Skills</label><input class="form-control" name="skills" value="<?=htmlspecialchars($get('skills'))?>" placeholder="Strategy, Project Management, Partnerships"><small>Separate skills with commas.</small></div><div class="form-group span-2"><label>Internal Notes</label><textarea class="form-control" rows="4" name="internal_notes"><?=htmlspecialchars($get('internal_notes'))?></textarea><small>Only administrators can see these notes.</small></div></div></section>
<div class="staff-form-submit"><button class="btn btn-primary" type="submit"><i data-lucide="save"></i> <?=$edit?'Update Staff Profile':'Create Staff & Business Card'?></button></div></form>
