<?php
$photoPath=$card['photo_filename']?media_url(['folder'=>$card['photo_folder'],'filename'=>$card['photo_filename']]):'';
$origin=preg_match('#^(https?://[^/]+)#',$cardUrl,$match)?$match[1]:'';
$ogImage=$photoPath?($origin&&str_starts_with($photoPath,'/')?$origin.$photoPath:$photoPath):$origin.url('/uploads/media/original/home/udyam-ventures-logo-cropped.png');
$phoneHref=preg_replace('/[^0-9+]/','',(string)$card['mobile']);$wa=preg_replace('/\D/','',(string)($card['whatsapp_number']?:$card['mobile']));
$description=trim($card['display_name'].' · '.$card['designation'].' at Udyam Ventures');
$e=static fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#071846"><title><?=$e($card['display_name'])?> | Udyam Ventures</title><meta name="description" content="<?=$e($description)?>"><link rel="canonical" href="<?=$e($cardUrl)?>"><link rel="icon" href="<?=$e(url('/favicon.ico'))?>"><meta property="og:type" content="profile"><meta property="og:title" content="<?=$e($card['display_name'].' | Udyam Ventures')?>"><meta property="og:description" content="<?=$e($description)?>"><meta property="og:url" content="<?=$e($cardUrl)?>"><meta property="og:image" content="<?=$e($ogImage)?>"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="<?=$e(url('/assets/website/css/digital-card.css').'?v='.(string)(@filemtime(ASSET_PATH.'/website/css/digital-card.css')?:'1'))?>"><link rel="stylesheet" href="<?=$e(url('/assets/website/css/digital-card-icons.css').'?v='.(string)(@filemtime(ASSET_PATH.'/website/css/digital-card-icons.css')?:'1'))?>"><script src="https://unpkg.com/lucide@latest" defer></script></head>
<body class="digital-card-page theme-<?=$e($card['theme'])?>"><div class="dc-ambient dc-one"></div><div class="dc-ambient dc-two"></div><main class="dc-shell"><section class="dc-card"><header class="dc-brand"><img src="<?=$e(url('/uploads/media/original/home/udyam-ventures-logo-cropped.png'))?>" alt="Udyam Ventures"><span>Digital Business Card</span></header><div class="dc-cover"><div class="dc-pattern"></div></div><div class="dc-profile"><div class="dc-photo"><?php if($photoPath):?><img src="<?=$e($photoPath)?>" alt="<?=$e($card['display_name'])?>" width="180" height="180"><?php else:?><span><?=$e(strtoupper(substr($card['first_name'],0,1).substr($card['last_name'],0,1)))?></span><?php endif?><i aria-label="Verified Udyam staff">✓</i></div><p class="dc-kicker">Udyam Ventures</p><h1><?=$e($card['display_name'])?></h1><h2><?=$e($card['designation'])?></h2><?php if($card['department']):?><p class="dc-department"><?=$e($card['department'])?></p><?php endif?></div>
<div class="dc-actions"><?php if($card['show_mobile']&&$card['mobile']):?><a href="tel:<?=$e($phoneHref)?>" data-event="call"><b><i data-lucide="phone"></i></b><span>Call</span></a><?php endif?><?php if($card['show_whatsapp']&&$wa):?><a href="https://wa.me/<?=$e($wa)?>?text=Hello%20<?=$e(rawurlencode($card['first_name']))?>" data-event="whatsapp" target="_blank" rel="noopener"><b><i data-lucide="message-circle-more"></i></b><span>WhatsApp</span></a><?php endif?><?php if($card['show_email']&&$card['email']):?><a href="mailto:<?=$e($card['email'])?>" data-event="email"><b><i data-lucide="mail"></i></b><span>Email</span></a><?php endif?><a href="<?=$e($vcardUrl)?>"><b><i data-lucide="user-round-plus"></i></b><span>Save Contact</span></a><button type="button" id="shareCard"><b><i data-lucide="share-2"></i></b><span>Share</span></button><?php if($card['website_url']):?><a href="<?=$e($card['website_url'])?>" data-event="website" target="_blank" rel="noopener"><b><i data-lucide="globe-2"></i></b><span>Website</span></a><?php endif?><?php if($card['show_linkedin']&&$card['linkedin_url']):?><a href="<?=$e($card['linkedin_url'])?>" data-event="linkedin" target="_blank" rel="noopener"><b><i data-lucide="briefcase-business"></i></b><span>LinkedIn</span></a><?php endif?></div>
<div class="dc-content"><?php if($card['show_bio']&&$card['bio']):?><section><span class="dc-label">About</span><p class="dc-bio"><?=nl2br($e($card['bio']))?></p></section><?php endif?><section><span class="dc-label">Connect</span><div class="dc-contact-list"><?php if($card['show_mobile']&&$card['mobile']):?><a href="tel:<?=$e($phoneHref)?>" data-event="call"><i><span data-lucide="phone"></span></i><span><small>Mobile</small><strong><?=$e($card['mobile'])?></strong></span><b>›</b></a><?php endif?><?php if($card['show_email']&&$card['email']):?><a href="mailto:<?=$e($card['email'])?>" data-event="email"><i><span data-lucide="mail"></span></i><span><small>Email</small><strong><?=$e($card['email'])?></strong></span><b>›</b></a><?php endif?><?php if($card['show_address']&&($card['address']||$card['office_location'])):?><div><i><span data-lucide="map-pin"></span></i><span><small>Office</small><strong><?=$e($card['office_location'])?></strong><em><?=$e($card['address'])?></em></span></div><?php endif?></div></section></div>
<footer><div class="dc-tagline"><span></span><p><small>Udyam Ventures</small>Enabling enterprise. Accelerating impact.</p></div><p class="dc-powered">Official digital identity · <?=$e($card['employee_code'])?></p></footer></section><p class="dc-toast" id="copyToast" role="status">Card link copied</p></main>
<script>document.addEventListener('DOMContentLoaded',()=>{if(window.lucide)lucide.createIcons({attrs:{'stroke-width':1.8}})});const endpoint=<?=json_encode(url('/card/'.$card['public_slug'].'/event'),JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>,cardUrl=<?=json_encode($cardUrl,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;function track(event){const body=new URLSearchParams({event});if(navigator.sendBeacon)navigator.sendBeacon(endpoint,body);else fetch(endpoint,{method:'POST',body,keepalive:true})}document.querySelectorAll('[data-event]').forEach(el=>el.addEventListener('click',()=>track(el.dataset.event)));document.getElementById('shareCard').addEventListener('click',async()=>{if(navigator.share){try{await navigator.share({title:<?=json_encode($card['display_name'].' | Udyam Ventures',JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>,text:<?=json_encode($description,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>,url:cardUrl});track('share')}catch(e){}}else{await navigator.clipboard.writeText(cardUrl);track('copy_link');const t=document.getElementById('copyToast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}});</script></body></html>
