<?php
$hero = $sections['page_hero'] ?? [];
$blocks = $sections['content_blocks']['items'] ?? [];
$features = $sections['feature_grid'] ?? [];
$statements = $sections['profile_statements'] ?? [];
$expertise = $sections['expertise_grid'] ?? [];
$contactDetails = $sections['contact_details'] ?? [];
$stats = $sections['page_stats']['items'] ?? [];
$faqs = $sections['page_faqs'] ?? [];
$cta = $sections['page_cta'] ?? [];
?>
<?php require __DIR__ . '/partials/site-header.php'; ?>
<main class="sectioned-page page-<?= htmlspecialchars((string) ($page['slug'] ?? 'standard')) ?>">
    <?php if ($hero): ?>
        <section class="inner-hero<?= !empty($hero['image_url']) ? ' has-background' : '' ?>"<?php if (!empty($hero['image_url'])): ?> style="background-image:url('<?= htmlspecialchars(public_url((string) $hero['image_url']), ENT_QUOTES) ?>')"<?php endif; ?>>
            <div class="inner-hero-content">
                <small><?= htmlspecialchars($hero['eyebrow'] ?? '') ?></small>
                <h1><?= htmlspecialchars($hero['heading'] ?? $page['title']) ?></h1>
                <p><?= nl2br(htmlspecialchars($hero['description'] ?? '')) ?></p>
                <?php if (!empty($hero['primary_button_label']) || !empty($hero['secondary_button_label'])): ?>
                    <div class="inner-hero-actions">
                        <?php if (!empty($hero['primary_button_label'])): ?><a class="primary<?= str_contains(strtolower((string) $hero['primary_button_label']), 'consultation') ? ' consultation-trigger' : '' ?>" href="<?= htmlspecialchars(url($hero['primary_button_url'] ?? '#')) ?>"><?= htmlspecialchars($hero['primary_button_label']) ?> <span>→</span></a><?php endif; ?>
                        <?php if (!empty($hero['secondary_button_label'])): ?><a class="secondary<?= str_contains(strtolower((string) $hero['secondary_button_label']), 'consultation') ? ' consultation-trigger' : '' ?>" href="<?= htmlspecialchars(url($hero['secondary_button_url'] ?? '#')) ?>"><?= htmlspecialchars($hero['secondary_button_label']) ?> <span>→</span></a><?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        </section>
    <?php endif; ?>
    <?php foreach ($blocks as $index => $block): ?><section class="content-block <?= $index % 2 ? 'reverse' : '' ?>"><div><h2><?= htmlspecialchars($block['heading'] ?? '') ?></h2><p><?= nl2br(htmlspecialchars($block['content'] ?? '')) ?></p></div><?php if (!empty($block['image_url'])): ?><img src="<?= htmlspecialchars(public_url((string) $block['image_url'])) ?>" alt=""><?php endif; ?></section><?php endforeach; ?>
    <?php if ($features): ?><section class="inner-section"><div class="section-heading"><h2><?= htmlspecialchars($features['heading'] ?? '') ?></h2><p><?= htmlspecialchars($features['description'] ?? '') ?></p></div><div class="feature-grid"><?php foreach (($features['items'] ?? []) as $item): ?><article><span><?= htmlspecialchars(($item['icon'] ?? '◇') === '$' ? '₹' : ($item['icon'] ?? '◇')) ?></span><h3><?= htmlspecialchars($item['title'] ?? '') ?></h3><p><?= htmlspecialchars($item['description'] ?? '') ?></p></article><?php endforeach; ?></div></section><?php endif; ?>
    <?php if ($statements): ?><section class="profile-statements"><div class="premium-section-heading"><small><?= htmlspecialchars($statements['eyebrow'] ?? '') ?></small><h2><?= htmlspecialchars($statements['heading'] ?? '') ?></h2><p><?= htmlspecialchars($statements['description'] ?? '') ?></p></div><div class="statement-grid"><?php foreach (($statements['items'] ?? []) as $index => $item): ?><article class="statement-card statement-tone-<?= ($index % 3) + 1 ?>"><span><?= htmlspecialchars($item['icon'] ?? '◇') ?></span><small>0<?= $index + 1 ?></small><h3><?= htmlspecialchars($item['title'] ?? '') ?></h3><p><?= nl2br(htmlspecialchars($item['content'] ?? '')) ?></p></article><?php endforeach; ?></div></section><?php endif; ?>
    <?php if ($expertise): ?><section class="expertise-section" id="areas-of-expertise"><div class="premium-section-heading"><small><?= htmlspecialchars($expertise['eyebrow'] ?? '') ?></small><h2><?= htmlspecialchars($expertise['heading'] ?? '') ?></h2><p><?= htmlspecialchars($expertise['description'] ?? '') ?></p></div><div class="expertise-grid"><?php foreach (($expertise['items'] ?? []) as $index => $item): ?><article class="expertise-card"><div class="expertise-card-top"><span><?= htmlspecialchars($item['icon'] ?? '◇') ?></span><small><?= str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT) ?></small></div><h3><?= htmlspecialchars($item['title'] ?? '') ?></h3><p><?= nl2br(htmlspecialchars($item['description'] ?? '')) ?></p><i aria-hidden="true">↗</i></article><?php endforeach; ?></div></section><?php endif; ?>
    <?php if ($contactDetails): ?><section class="contact-details-section" id="contact-details"><div class="premium-section-heading"><small><?= htmlspecialchars($contactDetails['eyebrow'] ?? '') ?></small><h2><?= htmlspecialchars($contactDetails['heading'] ?? '') ?></h2><p><?= htmlspecialchars($contactDetails['description'] ?? '') ?></p></div><div class="office-grid"><?php foreach (($contactDetails['offices'] ?? []) as $index => $office): ?><?php $mapQuery = trim((string) ($office['map_query'] ?? $office['address'] ?? '')); ?><article class="office-card"><div class="office-map"><iframe src="https://www.google.com/maps?q=<?= rawurlencode($mapQuery) ?>&amp;output=embed" title="<?= htmlspecialchars($office['title'] ?? 'Office') ?> location map" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><a href="https://www.google.com/maps/search/?api=1&amp;query=<?= rawurlencode($mapQuery) ?>" target="_blank" rel="noopener">Open in Google Maps <span>↗</span></a></div><div class="office-copy"><span>0<?= $index + 1 ?></span><small><?= $index === 0 ? 'Registered Presence' : 'Corporate Presence' ?></small><h3><?= htmlspecialchars($office['title'] ?? '') ?></h3><p><?= nl2br(htmlspecialchars($office['address'] ?? '')) ?></p></div></article><?php endforeach; ?></div><div class="contact-channel-panel"><div><small>Direct Connections</small><h2>Talk to the right Udyam team.</h2><p>For partnerships, projects, institutional advisory and general enquiries, connect through the channel most convenient for you.</p></div><div class="contact-channel-list"><?php foreach (($contactDetails['contact_lines'] ?? []) as $line): ?><?php $isEmail = strtolower((string) ($line['type'] ?? '')) === 'email'; ?><a href="<?= htmlspecialchars($line['url'] ?? ($isEmail ? 'mailto:' : 'tel:') . ($line['value'] ?? '')) ?>"><i><?= $isEmail ? '✉' : '⌕' ?></i><span><small><?= htmlspecialchars($line['label'] ?? ($isEmail ? 'Email' : 'Call')) ?></small><strong><?= htmlspecialchars($line['value'] ?? '') ?></strong></span><b>↗</b></a><?php endforeach; ?></div></div></section><?php endif; ?>
    <?php if ($stats): ?><section class="page-stat-strip"><?php foreach ($stats as $stat): ?><div><strong><?= htmlspecialchars($stat['value'] ?? '') ?></strong><span><?= htmlspecialchars($stat['label'] ?? '') ?></span></div><?php endforeach; ?></section><?php endif; ?>
    <?php if ($faqs): ?><section class="inner-section faq-section"><div class="section-heading"><h2><?= htmlspecialchars($faqs['heading'] ?? '') ?></h2></div><?php foreach (($faqs['items'] ?? []) as $item): ?><details><summary><?= htmlspecialchars($item['question'] ?? '') ?></summary><p><?= nl2br(htmlspecialchars($item['answer'] ?? '')) ?></p></details><?php endforeach; ?></section><?php endif; ?>
    <?php if ($cta): ?><section class="closing-cta"><div><h2><?= htmlspecialchars($cta['heading'] ?? '') ?></h2><p><?= htmlspecialchars($cta['description'] ?? '') ?></p></div><a class="<?= str_contains(strtolower((string) ($cta['button_label'] ?? '')), 'consultation') ? 'consultation-trigger' : '' ?>" href="<?= htmlspecialchars(url($cta['button_url'] ?? '#')) ?>"><?= htmlspecialchars($cta['button_label'] ?? 'Get Started') ?> →</a></section><?php endif; ?>
</main>
<?php require __DIR__ . '/partials/site-footer.php'; ?>
