<?php $pages=max(1,(int)ceil($total/20)); ?>
<div class="page-header"><div><span class="staff-eyebrow">Udyam Ventures</span><h2>Digital Business Cards</h2><p>Manage public staff cards, QR codes and engagement.</p></div></div>
<div class="card">
<form method="get" class="filters-bar staff-filters"><input class="form-control" name="search" value="<?=htmlspecialchars($search)?>" placeholder="Search staff, designation or card URL…"><select class="form-control" name="status"><option value="">All card statuses</option><option value="enabled" <?=$status==='enabled'?'selected':''?>>Enabled</option><option value="disabled" <?=$status==='disabled'?'selected':''?>>Disabled</option></select><button class="btn">Filter</button></form>
<div class="table-responsive"><table class="table staff-table"><thead><tr><th>Staff</th><th>Designation</th><th>Card Status</th><th>Card URL</th><th>QR</th><th>Views</th><th>Last Viewed</th><th>Created</th><th>Actions</th></tr></thead><tbody>
<?php if($cards===[]):?><tr><td colspan="9"><div class="staff-empty"><strong>No digital cards found</strong><span>Cards are created automatically with staff records.</span></div></td></tr>
<?php else:foreach($cards as $card):$public=$cardService->publicUrl($card);?><tr>
<td><a class="staff-person" href="<?=htmlspecialchars(url('/admin/staff/'.$card['user_id']))?>"><?php if($card['photo_filename']):?><img src="<?=htmlspecialchars(media_url(['folder'=>$card['photo_folder'],'filename'=>$card['photo_filename']]))?>" alt=""><?php else:?><span><?=htmlspecialchars(strtoupper(substr($card['display_name'],0,2)))?></span><?php endif?><div><strong><?=htmlspecialchars($card['display_name'])?></strong><small><?=htmlspecialchars($card['employee_code'])?></small></div></a></td>
<td><?=htmlspecialchars($card['designation'])?><small class="table-subtext"><?=htmlspecialchars($card['department'])?></small></td>
<td><span class="staff-status status-<?=$card['status']==='enabled'?'active':'inactive'?>"><?=htmlspecialchars(ucfirst($card['status']))?></span></td>
<td><button class="card-url-copy" data-copy="<?=htmlspecialchars($public,ENT_QUOTES)?>" title="Copy link"><code><?=htmlspecialchars($card['public_slug'])?></code><i data-lucide="copy"></i></button></td>
<td><a class="qr-thumb" href="<?=htmlspecialchars(url('/admin/digital-business-cards/'.$card['user_id'].'/qr?download=1'))?>"><img src="<?=htmlspecialchars(url('/admin/digital-business-cards/'.$card['user_id'].'/qr?format=svg'))?>" alt="QR"><span>Download</span></a></td>
<td><strong><?=number_format((int)$card['total_views'])?></strong><small class="table-subtext"><?=number_format((int)$card['qr_scans'])?> scans</small></td><td><?=$card['last_viewed_at']?htmlspecialchars(date('d M Y',strtotime($card['last_viewed_at']))):'Never'?></td><td><?=htmlspecialchars(date('d M Y',strtotime($card['created_at'])))?></td>
<td><div class="row-actions"><a class="btn btn-sm" target="_blank" href="<?=htmlspecialchars($public)?>">Preview</a><a class="btn btn-sm" href="<?=htmlspecialchars(url('/admin/digital-business-cards/'.$card['user_id'].'/qr?download=1'))?>">QR</a><a class="btn btn-sm" href="<?=htmlspecialchars(url('/admin/digital-business-cards/'.$card['user_id'].'/vcard'))?>">vCard</a><a class="btn btn-sm" href="<?=htmlspecialchars(url('/admin/digital-business-cards/'.$card['user_id'].'/edit'))?>">Settings</a><form method="post" action="<?=htmlspecialchars(url('/admin/digital-business-cards/'.$card['user_id'].'/toggle'))?>"><?=csrf_field()?><input type="hidden" name="return_to" value="/admin/digital-business-cards"><button class="btn btn-sm" type="submit"><?=$card['status']==='enabled'?'Disable':'Enable'?></button></form><form method="post" action="<?=htmlspecialchars(url('/admin/digital-business-cards/'.$card['user_id'].'/regenerate'))?>"><?=csrf_field()?><button class="btn btn-sm" type="submit">Regenerate</button></form></div></td>
</tr><?php endforeach;endif?></tbody></table></div>
<?php if($pages>1):?><div class="staff-pagination"><?php for($i=1;$i<=$pages;$i++):?><a class="<?=$i===$page?'active':''?>" href="<?=htmlspecialchars(url('/admin/digital-business-cards?'.http_build_query(['page'=>$i,'search'=>$search,'status'=>$status])))?>"><?=$i?></a><?php endfor?></div><?php endif?></div>
<script>document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{await navigator.clipboard.writeText(b.dataset.copy);b.classList.add('copied');setTimeout(()=>b.classList.remove('copied'),1200)}));</script>
