<section class="welcome-panel"><div><span>Welcome back</span><h2><?=htmlspecialchars($customer['first_name'])?>, your Udyam workspace is ready.</h2><p>Track services, applications, documents, subscriptions and billing from one secure place.</p></div><a href="<?=htmlspecialchars(url('/customer/services'))?>" class="primary-action">Explore services <i data-lucide="arrow-right"></i></a></section>
<section class="metric-grid">
<?php foreach([
['sparkles','Active Subscription',$data['subscription']['plan_name']??'No active plan'],
['clipboard-clock','Pending Applications',(string)$data['pendingApplications']],
['badge-check','Approved Services',(string)$data['approvedServices']],
['wallet-cards','Outstanding Payments','₹'.number_format((float)$data['outstanding'],2)]
] as $metric):?><article class="metric"><i data-lucide="<?=$metric[0]?>"></i><span><?=$metric[1]?></span><strong><?=htmlspecialchars($metric[2])?></strong></article><?php endforeach;?></section>
<div class="portal-grid two"><section class="portal-card"><div class="card-heading"><div><span>Billing</span><h3>Recent invoices</h3></div><a href="<?=htmlspecialchars(url('/customer/billing/invoices'))?>">View all</a></div><?php if(!$data['invoices']):?><div class="empty">No invoices yet.</div><?php else:?><div class="portal-list"><?php foreach($data['invoices'] as $row):?><a href="<?=htmlspecialchars(url('/customer/billing/invoices/'.$row['id']))?>"><span><strong><?=htmlspecialchars($row['invoice_number'])?></strong><small><?=htmlspecialchars($row['issue_date'])?></small></span><b>₹<?=number_format((float)$row['total_amount'],2)?></b></a><?php endforeach;?></div><?php endif;?></section>
<section class="portal-card"><div class="card-heading"><div><span>Updates</span><h3>Notifications</h3></div><a href="<?=htmlspecialchars(url('/customer/notifications'))?>">View all</a></div><?php if(!$data['notifications']):?><div class="empty">You are all caught up.</div><?php else:?><div class="portal-list"><?php foreach($data['notifications'] as $row):?><div><i data-lucide="bell-ring"></i><span><strong><?=htmlspecialchars($row['title'])?></strong><small><?=htmlspecialchars($row['message'])?></small></span></div><?php endforeach;?></div><?php endif;?></section></div>
<section class="portal-card"><div class="card-heading"><div><span>Audit trail</span><h3>Recent activity</h3></div><a href="<?=htmlspecialchars(url('/customer/activity'))?>">Full history</a></div><div class="timeline"><?php foreach($data['activity'] as $row):?><div><i></i><span><strong><?=htmlspecialchars(ucwords(str_replace('_',' ',$row['action'])))?></strong><small><?=htmlspecialchars($row['description']??'')?> · <?=htmlspecialchars($row['created_at'])?></small></span></div><?php endforeach;?></div></section>
