<?php
$benefits = json_decode((string) ($subscription['benefits'] ?? '[]'), true) ?: [];
$days = !empty($subscription['expires_at']) ? max(0, (int) floor((strtotime((string) $subscription['expires_at']) - strtotime('today')) / 86400)) : null;
?>
<div class="section-heading"><div><span>Membership</span><h2>My Subscription</h2><p>Manage your current plan, renewal details and service requests in one place.</p></div><a class="primary-action" href="<?= htmlspecialchars(url('/customer/plans')) ?>">View plans <i data-lucide="arrow-right"></i></a></div>
<?php if (!$subscription): ?><section class="portal-card subscription-empty"><i data-lucide="sparkles"></i><div><h3>No active membership</h3><p>Choose a Udyam membership to unlock project intelligence, notices and priority support.</p><a class="primary-action" href="<?= htmlspecialchars(url('/customer/plans')) ?>">Explore plans</a></div></section><?php else: ?>
<section class="portal-card my-subscription-card"><div class="my-subscription-head"><div><span class="subscription-status <?= htmlspecialchars((string) $subscription['status']) ?>"><?= htmlspecialchars(ucfirst((string) $subscription['status'])) ?></span><h3><?= htmlspecialchars((string) $subscription['plan_name']) ?></h3><p><?= htmlspecialchars((string) ($subscription['description'] ?? '')) ?></p></div><div class="subscription-days"><strong><?= $days === null ? '—' : $days ?></strong><span>days remaining</span></div></div><div class="subscription-details"><div><small>Activated</small><strong><?= htmlspecialchars((string) ($subscription['starts_at'] ?: '—')) ?></strong></div><div><small>Expiry / renewal</small><strong><?= htmlspecialchars((string) ($subscription['expires_at'] ?: '—')) ?></strong></div><div><small>Billing cycle</small><strong><?= htmlspecialchars(ucwords(str_replace('_', ' ', (string) $subscription['billing_cycle']))) ?></strong></div><div><small>Plan value</small><strong>₹<?= number_format((float) $subscription['amount'], 0) ?></strong></div></div><div class="subscription-benefits"><h4>Included benefits</h4><ul><?php foreach ($benefits as $benefit): ?><li><i data-lucide="check"></i><?= htmlspecialchars(is_array($benefit) ? (string) ($benefit['title'] ?? '') : (string) $benefit) ?></li><?php endforeach; ?></ul></div><div class="subscription-actions"><a class="ghost-action" href="<?= htmlspecialchars(url('/customer/billing/invoices')) ?>"><i data-lucide="receipt-indian-rupee"></i> View invoices</a><?php if ($subscription['status'] === 'active'): ?><button class="ghost-action" type="button" data-subscription-request="pause"><i data-lucide="pause-circle"></i> Request pause</button><button class="text-danger-button" type="button" data-subscription-request="cancellation"><i data-lucide="circle-x"></i> Request cancellation</button><?php else: ?><button class="primary-action" type="button" data-subscription-request="resume"><i data-lucide="play-circle"></i> Request resume</button><?php endif; ?></div></section>
<form class="subscription-request-form" method="post" action="<?= htmlspecialchars(url('/customer/subscription/request')) ?>" hidden><?= csrf_field() ?><input type="hidden" name="subscription_id" value="<?= (int) $subscription['id'] ?>"><input type="hidden" name="request_type"><div><h3 data-subscription-request-title>Subscription request</h3><p>Tell us why you are making this request. An administrator will review it before your membership changes.</p><textarea name="reason" required maxlength="1500" placeholder="Please share the reason for your request"></textarea><div><button class="ghost-action" type="button" data-subscription-request-close>Cancel</button><button class="primary-action" type="submit">Send request</button></div></div></form>
<?php endif; ?>
<section class="portal-card subscription-request-history"><div class="card-heading"><div><span>Request history</span><h3>Membership requests</h3></div></div><?php if (!$requests): ?><div class="empty">There are no pause, resume or cancellation requests yet.</div><?php else: ?><div class="portal-list"><?php foreach ($requests as $request): ?><div><i data-lucide="<?= $request['request_type'] === 'cancellation' ? 'circle-x' : ($request['request_type'] === 'pause' ? 'pause-circle' : 'play-circle') ?>"></i><span><strong><?= htmlspecialchars(ucfirst((string) $request['request_type'])) ?> request · <?= htmlspecialchars((string) $request['plan_name']) ?></strong><small><?= htmlspecialchars((string) ($request['reason'] ?: 'No reason provided')) ?> · <?= htmlspecialchars(date('d M Y', strtotime((string) $request['created_at']))) ?></small></span><b class="subscription-status <?= htmlspecialchars((string) $request['status']) ?>"><?= htmlspecialchars(ucfirst((string) $request['status'])) ?></b></div><?php endforeach; ?></div><?php endif; ?></section>
<script>document.addEventListener('DOMContentLoaded',function(){const form=document.querySelector('.subscription-request-form');document.querySelectorAll('[data-subscription-request]').forEach(function(button){button.addEventListener('click',function(){form.hidden=false;form.querySelector('[name="request_type"]').value=button.dataset.subscriptionRequest;form.querySelector('[data-subscription-request-title]').textContent='Request '+button.dataset.subscriptionRequest;form.scrollIntoView({behavior:'smooth',block:'center'});});});document.querySelector('[data-subscription-request-close]')?.addEventListener('click',function(){form.hidden=true;});});</script>
