<?php
$pages=max(1,(int)ceil($total/$perPage));
$filters=$filters??['q'=>'','region'=>'','invited_by'=>'','sort'=>'latest'];
$options=$filterOptions??['regions'=>[],'organisations'=>[]];
$queryUrl=static function(array $changes) use ($filters,$perPage): string { return '?' . http_build_query(array_merge($filters,['per_page'=>$perPage],$changes)); };
?>
<section class="tender-portal-hero"><div><span>Partner opportunity desk</span><h2>Notices &amp; Tenders</h2><p>Explore current, curated opportunities available through your active Udyam membership.</p></div><i data-lucide="megaphone"></i></section>
<section class="portal-card tender-directory">
    <div class="card-heading tender-directory-heading"><div><span>Current opportunities</span><h3><?= (int)$total ?> listing<?= $total===1?'':'s' ?> available</h3></div><label class="portal-page-size">Show <select form="tender-filters" name="per_page" onchange="this.form.submit()"><option value="10" <?= $perPage===10?'selected':'' ?>>10</option><option value="50" <?= $perPage===50?'selected':'' ?>>50</option><option value="100" <?= $perPage===100?'selected':'' ?>>100</option></select></label></div>
    <form id="tender-filters" class="tender-filter-bar" method="get" action="<?= htmlspecialchars(url('/customer/tenders')) ?>">
        <label class="tender-search"><i data-lucide="search"></i><span class="sr-only">Search notices and tenders</span><input name="q" value="<?= htmlspecialchars((string)$filters['q']) ?>" autocomplete="off" placeholder="Search by keyword, title, state…"></label>
        <span class="tender-filter-label"><i data-lucide="sliders-horizontal"></i> Filters</span>
        <select name="region" aria-label="Filter by state" onchange="this.form.submit()"><option value="">All states</option><?php foreach($options['regions'] as $region): ?><option value="<?=htmlspecialchars($region)?>" <?= $filters['region']===$region?'selected':'' ?>><?=htmlspecialchars($region)?></option><?php endforeach; ?></select>
        <select name="invited_by" aria-label="Filter by organisation" onchange="this.form.submit()"><option value="">All organisations</option><?php foreach($options['organisations'] as $organisation): ?><option value="<?=htmlspecialchars($organisation)?>" <?= $filters['invited_by']===$organisation?'selected':'' ?>><?=htmlspecialchars($organisation)?></option><?php endforeach; ?></select>
        <select name="sort" aria-label="Sort or filter listings" onchange="this.form.submit()"><option value="latest" <?= $filters['sort']==='latest'?'selected':'' ?>>Latest Date First</option><option value="deadline" <?= $filters['sort']==='deadline'?'selected':'' ?>>All Dated Tenders</option><option value="expired" <?= $filters['sort']==='expired'?'selected':'' ?>>Expired</option><option value="ongoing" <?= $filters['sort']==='ongoing'?'selected':'' ?>>Ongoing</option></select>
        <?php if($filters['q']!==''||$filters['region']!==''||$filters['invited_by']!==''||$filters['sort']!=='latest'): ?><a class="tender-reset" href="<?=htmlspecialchars(url('/customer/tenders?per_page='.$perPage))?>">Clear</a><?php endif; ?>
    </form>
    <?php if(!$tenders): ?><div class="empty">No notices or tenders match these filters. Try clearing a filter or searching with another keyword.</div><?php else: ?><div class="tender-directory-list"><?php foreach($tenders as $item): $deadline=(string)($item['deadline_label']??$item['closing_date']??'Open throughout year'); ?><a href="<?=htmlspecialchars(url('/customer/tenders/'.(int)$item['id']))?>"><span class="tender-directory-type <?=htmlspecialchars((string)($item['type']??'tender'))?>"><?=htmlspecialchars(ucfirst((string)($item['type']??'Tender')))?></span><div><strong><?=htmlspecialchars((string)$item['title'])?></strong><small><?=htmlspecialchars((string)($item['invited_by']??$item['department']??'Udyam opportunity desk'))?> · <?=htmlspecialchars((string)($item['region']??'PAN INDIA'))?></small></div><time><?=htmlspecialchars($deadline)?></time><i data-lucide="arrow-up-right"></i></a><?php endforeach;?></div><?php if($pages>1): ?><nav class="portal-pagination" aria-label="Tender listing pages"><?php for($i=1;$i<=$pages;$i++): ?><a class="<?= $i===$page?'active':'' ?>" href="<?=htmlspecialchars($queryUrl(['page'=>$i]))?>"><?=$i?></a><?php endfor;?></nav><?php endif; ?><?php endif;?>
</section>
<script>document.addEventListener('DOMContentLoaded',function(){const input=document.querySelector('#tender-filters input[name="q"]');if(!input)return;let timer;input.addEventListener('input',function(){clearTimeout(timer);timer=setTimeout(function(){input.form.submit()},450)})});</script>
